// src/app/sightings/page.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { getSightingsList, type Sighting } from "@/lib/species";
import { useAuth } from "@/app/context/AuthContext";
import { useRouter } from "next/navigation";

export default function SightingsListPage() {
  const [sightings, setSightings] = useState<Sighting[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const { isAuthenticated } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/login?redirect=/sightings");
      return;
    }
    loadSightings();
  }, [isAuthenticated]);

  async function loadSightings() {
    setLoading(true);
    setError("");
    try {
      const data = await getSightingsList({ limit: 50 });
      setSightings(data.sightings || []);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to load sightings."
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold text-forest">Sightings</h1>
        <Link
          href="/sightings/create"
          className="bg-leaf text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-leaf-light transition-colors"
        >
          + Report New Sighting
        </Link>
      </div>

      {loading && (
        <div className="text-center py-12 text-forest-light">
          Loading sightings...
        </div>
      )}

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-md">
          {error}
        </div>
      )}

      {!loading && !error && sightings.length === 0 && (
        <div className="text-center py-12">
          <p className="text-forest-light text-lg">
            No sightings have been reported yet.
          </p>
          <Link
            href="/sightings/create"
            className="text-leaf hover:text-leaf-light font-medium mt-2 inline-block"
          >
            Be the first to report one!
          </Link>
        </div>
      )}

      <div className="space-y-4">
        {sightings.map((s) => (
          <div
            key={s.id}
            className="bg-white rounded-xl p-5 shadow-sm border border-sky"
          >
            <div className="flex gap-4">
              {s.image_url && (
                <img
                  src={s.image_url}
                  alt="Sighting"
                  className="w-24 h-24 object-cover rounded-lg"
                />
              )}
              <div className="flex-1">
                <h3 className="text-lg font-semibold text-forest">
                  {s.species_name || `Species #${s.species_id}`}
                </h3>
                {s.description && (
                  <p className="text-forest-light text-sm mt-1">
                    {s.description}
                  </p>
                )}
                <div className="flex gap-4 mt-2 text-xs text-earth">
                  {s.observed_at && (
                    <span>
                      Observed: {new Date(s.observed_at).toLocaleDateString()}
                    </span>
                  )}
                  {s.latitude && s.longitude && (
                    <span>
                      {s.latitude.toFixed(4)}, {s.longitude.toFixed(4)}
                    </span>
                  )}
                  {s.reported_by && <span>By: {s.reported_by}</span>}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// app/pages/sightings/index.vue
<template>
  <div class="max-w-4xl mx-auto">
    <h1 class="text-2xl font-bold text-[var(--color-forest)] mb-6">Sightings</h1>

    <div class="mb-6">
      <NuxtLink
        to="/sightings/create"
        class="bg-[var(--color-leaf)] text-white px-4 py-2 rounded-lg hover:bg-[var(--color-leaf-light)] transition-colors"
      >
        + Report a Sighting
      </NuxtLink>
    </div>

    <div v-if="loading" class="text-center py-12 text-gray-400">
      Loading sightings...
    </div>

    <div v-else-if="error" class="text-center py-12 text-red-500">
      {{ error }}
    </div>

    <div v-else-if="sightings.length === 0" class="text-center py-12 text-gray-400">
      No sightings reported yet. Be the first!
    </div>

    <div v-else class="space-y-4">
      <div
        v-for="sighting in sightings"
        :key="sighting.id"
        class="bg-white rounded-lg shadow p-5"
      >
        <div class="flex items-start justify-between">
          <div>
            <h3 class="font-semibold text-[var(--color-forest)]">
              {{ sighting.species_name || `Species #${sighting.species_id}` }}
            </h3>
            <p class="text-sm text-gray-500">
              {{ new Date(sighting.created_at).toLocaleDateString() }}
            </p>
          </div>
          <span
            v-if="sighting.location"
            class="text-xs text-gray-400 bg-gray-100 px-2 py-1 rounded"
          >
            {{ sighting.location }}
          </span>
        </div>
        <p v-if="sighting.description" class="text-sm text-gray-600 mt-2">
          {{ sighting.description }}
        </p>
        <img
          v-if="sighting.image_url"
          :src="sighting.image_url"
          alt="Sighting photo"
          class="mt-3 rounded-lg max-h-48 object-cover"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'auth',
})

interface Sighting {
  id: number
  species_id: number
  species_name?: string
  description?: string
  location?: string
  image_url?: string
  created_at: string
}

const loading = ref(true)
const error = ref<string | null>(null)
const sightings = ref<Sighting[]>([])

onMounted(async () => {
  try {
    sightings.value = await apiFetch<Sighting[]>('/api/species-sightings')
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : 'Failed to load sightings'
  } finally {
    loading.value = false
  }
})
</script>
