// src/app/species/[id]/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { getSpeciesById, type Species } from "@/lib/species";

export default function SpeciesDetailPage() {
  const params = useParams();
  const id = Number(params.id);
  const [species, setSpecies] = useState<Species | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!id) return;
    loadSpecies();
  }, [id]);

  async function loadSpecies() {
    setLoading(true);
    setError("");
    try {
      const data = await getSpeciesById(id);
      setSpecies(data);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to load species details."
      );
    } finally {
      setLoading(false);
    }
  }

  if (loading) {
    return (
      <div className="text-center py-12 text-forest-light">
        Loading species details...
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-md inline-block">
          {error}
        </div>
        <div className="mt-4">
          <Link
            href="/species"
            className="text-leaf hover:text-leaf-light font-medium"
          >
            &larr; Back to species list
          </Link>
        </div>
      </div>
    );
  }

  if (!species) return null;

  return (
    <div className="max-w-3xl mx-auto">
      <Link
        href="/species"
        className="text-leaf hover:text-leaf-light font-medium mb-6 inline-block"
      >
        &larr; Back to species list
      </Link>

      <div className="bg-white rounded-xl shadow-sm border border-sky overflow-hidden">
        {species.image_url && (
          <img
            src={species.image_url}
            alt={species.name}
            className="w-full h-64 object-cover"
          />
        )}

        <div className="p-6 space-y-4">
          <h1 className="text-3xl font-bold text-forest">{species.name}</h1>

          {species.scientific_name && (
            <p className="text-lg text-leaf italic">
              {species.scientific_name}
            </p>
          )}

          {species.conservation_status && (
            <div>
              <span className="text-sm font-medium text-forest">
                Conservation Status:{" "}
              </span>
              <span className="inline-block text-xs bg-sky text-forest-light px-3 py-1 rounded-full">
                {species.conservation_status}
              </span>
            </div>
          )}

          {species.description && (
            <div>
              <h2 className="text-xl font-semibold text-forest mb-2">
                Description
              </h2>
              <p className="text-forest-light leading-relaxed">
                {species.description}
              </p>
            </div>
          )}

          <div className="text-sm text-earth border-t border-sky pt-4">
            {species.created_at && (
              <p>First recorded: {new Date(species.created_at).toLocaleDateString()}</p>
            )}
            {species.updated_at && (
              <p>Last updated: {new Date(species.updated_at).toLocaleDateString()}</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// app/pages/species/[id].vue
<template>
  <div class="max-w-3xl mx-auto">
    <NuxtLink to="/species" class="text-[var(--color-leaf)] hover:underline text-sm mb-4 inline-block">
      &larr; Back to Species
    </NuxtLink>

    <div v-if="speciesStore.loading" class="text-center py-12 text-gray-400">
      Loading...
    </div>

    <div v-else-if="speciesStore.error" class="text-center py-12 text-red-500">
      {{ speciesStore.error }}
    </div>

    <div v-else-if="speciesStore.currentSpecies" class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="speciesStore.currentSpecies.image_url" class="h-64 bg-gray-100">
        <img
          :src="speciesStore.currentSpecies.image_url"
          :alt="speciesStore.currentSpecies.name"
          class="w-full h-full object-cover"
        />
      </div>
      <div class="p-6">
        <h1 class="text-3xl font-bold text-[var(--color-forest)]">
          {{ speciesStore.currentSpecies.name }}
        </h1>
        <p class="text-gray-400 italic text-lg mb-4">
          {{ speciesStore.currentSpecies.scientific_name }}
        </p>

        <span
          class="inline-block text-sm px-3 py-1 rounded-full mb-4"
          :class="statusBadgeClass(speciesStore.currentSpecies.conservation_status)"
        >
          {{ speciesStore.currentSpecies.conservation_status }}
        </span>

        <p class="text-gray-700 leading-relaxed">
          {{ speciesStore.currentSpecies.description }}
        </p>

        <p class="text-sm text-gray-400 mt-6">
          Last updated: {{ new Date(speciesStore.currentSpecies.updated_at).toLocaleDateString() }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'auth',
})

const route = useRoute()
const speciesStore = useSpeciesStore()

onMounted(() => {
  speciesStore.fetchById(route.params.id as string)
})

function statusBadgeClass(status: string) {
  const map: Record<string, string> = {
    'Endangered': 'bg-red-100 text-red-700',
    'Vulnerable': 'bg-orange-100 text-orange-700',
    'Near Threatened': 'bg-yellow-100 text-yellow-700',
    'Least Concern': 'bg-green-100 text-green-700',
    'Critically Endangered': 'bg-red-200 text-red-800',
    'Extinct in the Wild': 'bg-gray-200 text-gray-700',
  }
  return map[status] || 'bg-blue-100 text-blue-700'
}
</script>
