// app/pages/species/index.vue
<template>
  <div class="max-w-4xl mx-auto">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold text-[var(--color-forest)]">Species</h1>
      <p class="text-sm text-gray-500">{{ speciesStore.speciesList.length }} total</p>
    </div>

    <div v-if="speciesStore.loading" class="text-center py-12 text-gray-400">
      Loading species...
    </div>

    <div v-else-if="speciesStore.error" class="text-center py-12 text-red-500">
      {{ speciesStore.error }}
    </div>

    <div v-else-if="speciesStore.speciesList.length === 0" class="text-center py-12 text-gray-400">
      No species found yet.
    </div>

    <div v-else class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
      <NuxtLink
        v-for="species in speciesStore.speciesList"
        :key="species.id"
        :to="`/species/${species.id}`"
        class="bg-white rounded-lg shadow p-5 hover:shadow-md transition-shadow hover:border-l-4 hover:border-l-[var(--color-leaf)]"
      >
        <h2 class="font-semibold text-[var(--color-forest)] text-lg">{{ species.name }}</h2>
        <p class="text-sm text-gray-400 italic mb-2">{{ species.scientific_name }}</p>
        <p class="text-sm text-gray-600 line-clamp-2">{{ species.description }}</p>
        <span
          class="inline-block mt-3 text-xs px-2 py-0.5 rounded-full"
          :class="statusBadgeClass(species.conservation_status)"
        >
          {{ species.conservation_status }}
        </span>
      </NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'auth',
})

const speciesStore = useSpeciesStore()

onMounted(() => {
  speciesStore.fetchAll()
})

function statusBadgeClass(status: string) {
  const map: Record<string, string> = {
    'Endangered': 'bg-red-100 text-red-700',
    'Vulnerable': 'bg-orange-100 text-orange-700',
    'Near Threatened': 'bg-yellow-100 text-yellow-700',
    'Least Concern': 'bg-green-100 text-green-700',
    'Critically Endangered': 'bg-red-200 text-red-800',
    'Extinct in the Wild': 'bg-gray-200 text-gray-700',
  }
  return map[status] || 'bg-blue-100 text-blue-700'
}
</script>

// src/app/species/page.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { getSpeciesList, type Species } from "@/lib/species";

export default function SpeciesListPage() {
  const [species, setSpecies] = useState<Species[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");


  async function loadSpecies() {
    setLoading(true);
    setError("");
    try {
      const data = await getSpeciesList({ limit: 50 });
      setSpecies(data.species || []);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to load species."
      );
      // Use demo data for now
      setSpecies([]);
    } finally {
      setLoading(false);
    }
  }

  const filtered = search
    ? species.filter(
        (s) =>
          s.name.toLowerCase().includes(search.toLowerCase()) ||
          (s.scientific_name &&
            s.scientific_name.toLowerCase().includes(search.toLowerCase()))
      )
    : species;


  useEffect(() => {
    (async () => {
      await loadSpecies();
    })()
  }, []);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold text-forest">Species</h1>
      </div>

      {/* Search */}
      <div>
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search species by name or scientific name..."
          className="w-full max-w-md px-4 py-2 border border-leaf-light rounded-md bg-white text-forest placeholder:text-earth/50 focus:outline-none focus:ring-2 focus:ring-leaf"
        />
      </div>

      {loading && (
        <div className="text-center py-12 text-forest-light">
          Loading species...
        </div>
      )}

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-md">
          {error}
        </div>
      )}

      {!loading && !error && filtered.length === 0 && (
        <div className="text-center py-12">
          <p className="text-forest-light text-lg">
            {search
              ? "No species match your search."
              : "No species have been registered yet."}
          </p>
        </div>
      )}

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filtered.map((s) => (
          <Link
            key={s.id}
            href={`/species/${s.id}`}
            className="bg-white rounded-xl p-5 shadow-sm border border-sky hover:border-leaf hover:shadow-md transition-all"
          >
            {s.image_url && (
              <img
                src={s.image_url}
                alt={s.name}
                className="w-full h-40 object-cover rounded-lg mb-3"
              />
            )}
            <h3 className="text-lg font-semibold text-forest">{s.name}</h3>
            {s.scientific_name && (
              <p className="text-sm text-leaf italic">{s.scientific_name}</p>
            )}
            {s.conservation_status && (
              <span className="inline-block mt-2 text-xs bg-sky text-forest-light px-2 py-1 rounded-full">
                {s.conservation_status}
              </span>
            )}
          </Link>
        ))}
      </div>
    </div>
  );
}
